# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/rechenplan/Code/zyven/zquake

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/rechenplan/Code/zyven/zquake

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rechenplan/Code/zyven/zquake/CMakeFiles /home/rechenplan/Code/zyven/zquake//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rechenplan/Code/zyven/zquake/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named shaders

# Build rule for target.
shaders: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 shaders
.PHONY : shaders

# fast build rule for target.
shaders/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shaders.dir/build.make CMakeFiles/shaders.dir/build
.PHONY : shaders/fast

#=============================================================================
# Target rules for targets named zq_core

# Build rule for target.
zq_core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zq_core
.PHONY : zq_core

# fast build rule for target.
zq_core/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_core.dir/build.make CMakeFiles/zq_core.dir/build
.PHONY : zq_core/fast

#=============================================================================
# Target rules for targets named zq_filesystem

# Build rule for target.
zq_filesystem: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zq_filesystem
.PHONY : zq_filesystem

# fast build rule for target.
zq_filesystem/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_filesystem.dir/build.make CMakeFiles/zq_filesystem.dir/build
.PHONY : zq_filesystem/fast

#=============================================================================
# Target rules for targets named zq_subsystems

# Build rule for target.
zq_subsystems: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zq_subsystems
.PHONY : zq_subsystems

# fast build rule for target.
zq_subsystems/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_subsystems.dir/build.make CMakeFiles/zq_subsystems.dir/build
.PHONY : zq_subsystems/fast

#=============================================================================
# Target rules for targets named zq_vulkan

# Build rule for target.
zq_vulkan: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zq_vulkan
.PHONY : zq_vulkan

# fast build rule for target.
zq_vulkan/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_vulkan.dir/build.make CMakeFiles/zq_vulkan.dir/build
.PHONY : zq_vulkan/fast

#=============================================================================
# Target rules for targets named zq_render

# Build rule for target.
zq_render: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zq_render
.PHONY : zq_render

# fast build rule for target.
zq_render/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_render.dir/build.make CMakeFiles/zq_render.dir/build
.PHONY : zq_render/fast

#=============================================================================
# Target rules for targets named zq_engine

# Build rule for target.
zq_engine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zq_engine
.PHONY : zq_engine

# fast build rule for target.
zq_engine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_engine.dir/build.make CMakeFiles/zq_engine.dir/build
.PHONY : zq_engine/fast

#=============================================================================
# Target rules for targets named zq_vm

# Build rule for target.
zq_vm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zq_vm
.PHONY : zq_vm

# fast build rule for target.
zq_vm/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_vm.dir/build.make CMakeFiles/zq_vm.dir/build
.PHONY : zq_vm/fast

#=============================================================================
# Target rules for targets named zquake

# Build rule for target.
zquake: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zquake
.PHONY : zquake

# fast build rule for target.
zquake/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake.dir/build.make CMakeFiles/zquake.dir/build
.PHONY : zquake/fast

#=============================================================================
# Target rules for targets named zquake_tests

# Build rule for target.
zquake_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zquake_tests
.PHONY : zquake_tests

# fast build rule for target.
zquake_tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_tests.dir/build.make CMakeFiles/zquake_tests.dir/build
.PHONY : zquake_tests/fast

#=============================================================================
# Target rules for targets named zquake_smoke

# Build rule for target.
zquake_smoke: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zquake_smoke
.PHONY : zquake_smoke

# fast build rule for target.
zquake_smoke/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_smoke.dir/build.make CMakeFiles/zquake_smoke.dir/build
.PHONY : zquake_smoke/fast

#=============================================================================
# Target rules for targets named zquake_orientation

# Build rule for target.
zquake_orientation: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zquake_orientation
.PHONY : zquake_orientation

# fast build rule for target.
zquake_orientation/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_orientation.dir/build.make CMakeFiles/zquake_orientation.dir/build
.PHONY : zquake_orientation/fast

#=============================================================================
# Target rules for targets named zquake_realdata

# Build rule for target.
zquake_realdata: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zquake_realdata
.PHONY : zquake_realdata

# fast build rule for target.
zquake_realdata/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_realdata.dir/build.make CMakeFiles/zquake_realdata.dir/build
.PHONY : zquake_realdata/fast

#=============================================================================
# Target rules for targets named zquake_inspect

# Build rule for target.
zquake_inspect: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zquake_inspect
.PHONY : zquake_inspect

# fast build rule for target.
zquake_inspect/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_inspect.dir/build.make CMakeFiles/zquake_inspect.dir/build
.PHONY : zquake_inspect/fast

#=============================================================================
# Target rules for targets named zquake_spawnview

# Build rule for target.
zquake_spawnview: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zquake_spawnview
.PHONY : zquake_spawnview

# fast build rule for target.
zquake_spawnview/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_spawnview.dir/build.make CMakeFiles/zquake_spawnview.dir/build
.PHONY : zquake_spawnview/fast

#=============================================================================
# Target rules for targets named zquake_raytrace

# Build rule for target.
zquake_raytrace: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zquake_raytrace
.PHONY : zquake_raytrace

# fast build rule for target.
zquake_raytrace/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_raytrace.dir/build.make CMakeFiles/zquake_raytrace.dir/build
.PHONY : zquake_raytrace/fast

#=============================================================================
# Target rules for targets named Catch2

# Build rule for target.
Catch2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Catch2
.PHONY : Catch2

# fast build rule for target.
Catch2/fast:
	$(MAKE) $(MAKESILENT) -f _deps/catch2-build/src/CMakeFiles/Catch2.dir/build.make _deps/catch2-build/src/CMakeFiles/Catch2.dir/build
.PHONY : Catch2/fast

#=============================================================================
# Target rules for targets named Catch2WithMain

# Build rule for target.
Catch2WithMain: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Catch2WithMain
.PHONY : Catch2WithMain

# fast build rule for target.
Catch2WithMain/fast:
	$(MAKE) $(MAKESILENT) -f _deps/catch2-build/src/CMakeFiles/Catch2WithMain.dir/build.make _deps/catch2-build/src/CMakeFiles/Catch2WithMain.dir/build
.PHONY : Catch2WithMain/fast

src/app/entry_point.o: src/app/entry_point.cpp.o
.PHONY : src/app/entry_point.o

# target to build an object file
src/app/entry_point.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake.dir/build.make CMakeFiles/zquake.dir/src/app/entry_point.cpp.o
.PHONY : src/app/entry_point.cpp.o

src/app/entry_point.i: src/app/entry_point.cpp.i
.PHONY : src/app/entry_point.i

# target to preprocess a source file
src/app/entry_point.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake.dir/build.make CMakeFiles/zquake.dir/src/app/entry_point.cpp.i
.PHONY : src/app/entry_point.cpp.i

src/app/entry_point.s: src/app/entry_point.cpp.s
.PHONY : src/app/entry_point.s

# target to generate assembly for a file
src/app/entry_point.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake.dir/build.make CMakeFiles/zquake.dir/src/app/entry_point.cpp.s
.PHONY : src/app/entry_point.cpp.s

src/app/rt_scene.o: src/app/rt_scene.cpp.o
.PHONY : src/app/rt_scene.o

# target to build an object file
src/app/rt_scene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_render.dir/build.make CMakeFiles/zq_render.dir/src/app/rt_scene.cpp.o
.PHONY : src/app/rt_scene.cpp.o

src/app/rt_scene.i: src/app/rt_scene.cpp.i
.PHONY : src/app/rt_scene.i

# target to preprocess a source file
src/app/rt_scene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_render.dir/build.make CMakeFiles/zq_render.dir/src/app/rt_scene.cpp.i
.PHONY : src/app/rt_scene.cpp.i

src/app/rt_scene.s: src/app/rt_scene.cpp.s
.PHONY : src/app/rt_scene.s

# target to generate assembly for a file
src/app/rt_scene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_render.dir/build.make CMakeFiles/zq_render.dir/src/app/rt_scene.cpp.s
.PHONY : src/app/rt_scene.cpp.s

src/app/world_builder.o: src/app/world_builder.cpp.o
.PHONY : src/app/world_builder.o

# target to build an object file
src/app/world_builder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake.dir/build.make CMakeFiles/zquake.dir/src/app/world_builder.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_orientation.dir/build.make CMakeFiles/zquake_orientation.dir/src/app/world_builder.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_spawnview.dir/build.make CMakeFiles/zquake_spawnview.dir/src/app/world_builder.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_raytrace.dir/build.make CMakeFiles/zquake_raytrace.dir/src/app/world_builder.cpp.o
.PHONY : src/app/world_builder.cpp.o

src/app/world_builder.i: src/app/world_builder.cpp.i
.PHONY : src/app/world_builder.i

# target to preprocess a source file
src/app/world_builder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake.dir/build.make CMakeFiles/zquake.dir/src/app/world_builder.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_orientation.dir/build.make CMakeFiles/zquake_orientation.dir/src/app/world_builder.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_spawnview.dir/build.make CMakeFiles/zquake_spawnview.dir/src/app/world_builder.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_raytrace.dir/build.make CMakeFiles/zquake_raytrace.dir/src/app/world_builder.cpp.i
.PHONY : src/app/world_builder.cpp.i

src/app/world_builder.s: src/app/world_builder.cpp.s
.PHONY : src/app/world_builder.s

# target to generate assembly for a file
src/app/world_builder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake.dir/build.make CMakeFiles/zquake.dir/src/app/world_builder.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_orientation.dir/build.make CMakeFiles/zquake_orientation.dir/src/app/world_builder.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_spawnview.dir/build.make CMakeFiles/zquake_spawnview.dir/src/app/world_builder.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_raytrace.dir/build.make CMakeFiles/zquake_raytrace.dir/src/app/world_builder.cpp.s
.PHONY : src/app/world_builder.cpp.s

src/core/container/string.o: src/core/container/string.cpp.o
.PHONY : src/core/container/string.o

# target to build an object file
src/core/container/string.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_core.dir/build.make CMakeFiles/zq_core.dir/src/core/container/string.cpp.o
.PHONY : src/core/container/string.cpp.o

src/core/container/string.i: src/core/container/string.cpp.i
.PHONY : src/core/container/string.i

# target to preprocess a source file
src/core/container/string.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_core.dir/build.make CMakeFiles/zq_core.dir/src/core/container/string.cpp.i
.PHONY : src/core/container/string.cpp.i

src/core/container/string.s: src/core/container/string.cpp.s
.PHONY : src/core/container/string.s

# target to generate assembly for a file
src/core/container/string.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_core.dir/build.make CMakeFiles/zq_core.dir/src/core/container/string.cpp.s
.PHONY : src/core/container/string.cpp.s

src/core/fixed/fixed_math.o: src/core/fixed/fixed_math.cpp.o
.PHONY : src/core/fixed/fixed_math.o

# target to build an object file
src/core/fixed/fixed_math.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_core.dir/build.make CMakeFiles/zq_core.dir/src/core/fixed/fixed_math.cpp.o
.PHONY : src/core/fixed/fixed_math.cpp.o

src/core/fixed/fixed_math.i: src/core/fixed/fixed_math.cpp.i
.PHONY : src/core/fixed/fixed_math.i

# target to preprocess a source file
src/core/fixed/fixed_math.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_core.dir/build.make CMakeFiles/zq_core.dir/src/core/fixed/fixed_math.cpp.i
.PHONY : src/core/fixed/fixed_math.cpp.i

src/core/fixed/fixed_math.s: src/core/fixed/fixed_math.cpp.s
.PHONY : src/core/fixed/fixed_math.s

# target to generate assembly for a file
src/core/fixed/fixed_math.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_core.dir/build.make CMakeFiles/zq_core.dir/src/core/fixed/fixed_math.cpp.s
.PHONY : src/core/fixed/fixed_math.cpp.s

src/core/fixed/fixed_t.o: src/core/fixed/fixed_t.cpp.o
.PHONY : src/core/fixed/fixed_t.o

# target to build an object file
src/core/fixed/fixed_t.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_core.dir/build.make CMakeFiles/zq_core.dir/src/core/fixed/fixed_t.cpp.o
.PHONY : src/core/fixed/fixed_t.cpp.o

src/core/fixed/fixed_t.i: src/core/fixed/fixed_t.cpp.i
.PHONY : src/core/fixed/fixed_t.i

# target to preprocess a source file
src/core/fixed/fixed_t.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_core.dir/build.make CMakeFiles/zq_core.dir/src/core/fixed/fixed_t.cpp.i
.PHONY : src/core/fixed/fixed_t.cpp.i

src/core/fixed/fixed_t.s: src/core/fixed/fixed_t.cpp.s
.PHONY : src/core/fixed/fixed_t.s

# target to generate assembly for a file
src/core/fixed/fixed_t.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_core.dir/build.make CMakeFiles/zq_core.dir/src/core/fixed/fixed_t.cpp.s
.PHONY : src/core/fixed/fixed_t.cpp.s

src/core/fixed/fixed_tables.o: src/core/fixed/fixed_tables.cpp.o
.PHONY : src/core/fixed/fixed_tables.o

# target to build an object file
src/core/fixed/fixed_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_core.dir/build.make CMakeFiles/zq_core.dir/src/core/fixed/fixed_tables.cpp.o
.PHONY : src/core/fixed/fixed_tables.cpp.o

src/core/fixed/fixed_tables.i: src/core/fixed/fixed_tables.cpp.i
.PHONY : src/core/fixed/fixed_tables.i

# target to preprocess a source file
src/core/fixed/fixed_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_core.dir/build.make CMakeFiles/zq_core.dir/src/core/fixed/fixed_tables.cpp.i
.PHONY : src/core/fixed/fixed_tables.cpp.i

src/core/fixed/fixed_tables.s: src/core/fixed/fixed_tables.cpp.s
.PHONY : src/core/fixed/fixed_tables.s

# target to generate assembly for a file
src/core/fixed/fixed_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_core.dir/build.make CMakeFiles/zq_core.dir/src/core/fixed/fixed_tables.cpp.s
.PHONY : src/core/fixed/fixed_tables.cpp.s

src/core/io/file_io.o: src/core/io/file_io.cpp.o
.PHONY : src/core/io/file_io.o

# target to build an object file
src/core/io/file_io.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_core.dir/build.make CMakeFiles/zq_core.dir/src/core/io/file_io.cpp.o
.PHONY : src/core/io/file_io.cpp.o

src/core/io/file_io.i: src/core/io/file_io.cpp.i
.PHONY : src/core/io/file_io.i

# target to preprocess a source file
src/core/io/file_io.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_core.dir/build.make CMakeFiles/zq_core.dir/src/core/io/file_io.cpp.i
.PHONY : src/core/io/file_io.cpp.i

src/core/io/file_io.s: src/core/io/file_io.cpp.s
.PHONY : src/core/io/file_io.s

# target to generate assembly for a file
src/core/io/file_io.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_core.dir/build.make CMakeFiles/zq_core.dir/src/core/io/file_io.cpp.s
.PHONY : src/core/io/file_io.cpp.s

src/core/logging/logger.o: src/core/logging/logger.cpp.o
.PHONY : src/core/logging/logger.o

# target to build an object file
src/core/logging/logger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_core.dir/build.make CMakeFiles/zq_core.dir/src/core/logging/logger.cpp.o
.PHONY : src/core/logging/logger.cpp.o

src/core/logging/logger.i: src/core/logging/logger.cpp.i
.PHONY : src/core/logging/logger.i

# target to preprocess a source file
src/core/logging/logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_core.dir/build.make CMakeFiles/zq_core.dir/src/core/logging/logger.cpp.i
.PHONY : src/core/logging/logger.cpp.i

src/core/logging/logger.s: src/core/logging/logger.cpp.s
.PHONY : src/core/logging/logger.s

# target to generate assembly for a file
src/core/logging/logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_core.dir/build.make CMakeFiles/zq_core.dir/src/core/logging/logger.cpp.s
.PHONY : src/core/logging/logger.cpp.s

src/core/memory/allocator.o: src/core/memory/allocator.cpp.o
.PHONY : src/core/memory/allocator.o

# target to build an object file
src/core/memory/allocator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_core.dir/build.make CMakeFiles/zq_core.dir/src/core/memory/allocator.cpp.o
.PHONY : src/core/memory/allocator.cpp.o

src/core/memory/allocator.i: src/core/memory/allocator.cpp.i
.PHONY : src/core/memory/allocator.i

# target to preprocess a source file
src/core/memory/allocator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_core.dir/build.make CMakeFiles/zq_core.dir/src/core/memory/allocator.cpp.i
.PHONY : src/core/memory/allocator.cpp.i

src/core/memory/allocator.s: src/core/memory/allocator.cpp.s
.PHONY : src/core/memory/allocator.s

# target to generate assembly for a file
src/core/memory/allocator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_core.dir/build.make CMakeFiles/zq_core.dir/src/core/memory/allocator.cpp.s
.PHONY : src/core/memory/allocator.cpp.s

src/engine/area_nodes.o: src/engine/area_nodes.cpp.o
.PHONY : src/engine/area_nodes.o

# target to build an object file
src/engine/area_nodes.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_engine.dir/build.make CMakeFiles/zq_engine.dir/src/engine/area_nodes.cpp.o
.PHONY : src/engine/area_nodes.cpp.o

src/engine/area_nodes.i: src/engine/area_nodes.cpp.i
.PHONY : src/engine/area_nodes.i

# target to preprocess a source file
src/engine/area_nodes.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_engine.dir/build.make CMakeFiles/zq_engine.dir/src/engine/area_nodes.cpp.i
.PHONY : src/engine/area_nodes.cpp.i

src/engine/area_nodes.s: src/engine/area_nodes.cpp.s
.PHONY : src/engine/area_nodes.s

# target to generate assembly for a file
src/engine/area_nodes.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_engine.dir/build.make CMakeFiles/zq_engine.dir/src/engine/area_nodes.cpp.s
.PHONY : src/engine/area_nodes.cpp.s

src/engine/bsp.o: src/engine/bsp.cpp.o
.PHONY : src/engine/bsp.o

# target to build an object file
src/engine/bsp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_engine.dir/build.make CMakeFiles/zq_engine.dir/src/engine/bsp.cpp.o
.PHONY : src/engine/bsp.cpp.o

src/engine/bsp.i: src/engine/bsp.cpp.i
.PHONY : src/engine/bsp.i

# target to preprocess a source file
src/engine/bsp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_engine.dir/build.make CMakeFiles/zq_engine.dir/src/engine/bsp.cpp.i
.PHONY : src/engine/bsp.cpp.i

src/engine/bsp.s: src/engine/bsp.cpp.s
.PHONY : src/engine/bsp.s

# target to generate assembly for a file
src/engine/bsp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_engine.dir/build.make CMakeFiles/zq_engine.dir/src/engine/bsp.cpp.s
.PHONY : src/engine/bsp.cpp.s

src/engine/console.o: src/engine/console.cpp.o
.PHONY : src/engine/console.o

# target to build an object file
src/engine/console.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_engine.dir/build.make CMakeFiles/zq_engine.dir/src/engine/console.cpp.o
.PHONY : src/engine/console.cpp.o

src/engine/console.i: src/engine/console.cpp.i
.PHONY : src/engine/console.i

# target to preprocess a source file
src/engine/console.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_engine.dir/build.make CMakeFiles/zq_engine.dir/src/engine/console.cpp.i
.PHONY : src/engine/console.cpp.i

src/engine/console.s: src/engine/console.cpp.s
.PHONY : src/engine/console.s

# target to generate assembly for a file
src/engine/console.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_engine.dir/build.make CMakeFiles/zq_engine.dir/src/engine/console.cpp.s
.PHONY : src/engine/console.cpp.s

src/engine/cvar_parser.o: src/engine/cvar_parser.cpp.o
.PHONY : src/engine/cvar_parser.o

# target to build an object file
src/engine/cvar_parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_engine.dir/build.make CMakeFiles/zq_engine.dir/src/engine/cvar_parser.cpp.o
.PHONY : src/engine/cvar_parser.cpp.o

src/engine/cvar_parser.i: src/engine/cvar_parser.cpp.i
.PHONY : src/engine/cvar_parser.i

# target to preprocess a source file
src/engine/cvar_parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_engine.dir/build.make CMakeFiles/zq_engine.dir/src/engine/cvar_parser.cpp.i
.PHONY : src/engine/cvar_parser.cpp.i

src/engine/cvar_parser.s: src/engine/cvar_parser.cpp.s
.PHONY : src/engine/cvar_parser.s

# target to generate assembly for a file
src/engine/cvar_parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_engine.dir/build.make CMakeFiles/zq_engine.dir/src/engine/cvar_parser.cpp.s
.PHONY : src/engine/cvar_parser.cpp.s

src/engine/cvar_system.o: src/engine/cvar_system.cpp.o
.PHONY : src/engine/cvar_system.o

# target to build an object file
src/engine/cvar_system.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_engine.dir/build.make CMakeFiles/zq_engine.dir/src/engine/cvar_system.cpp.o
.PHONY : src/engine/cvar_system.cpp.o

src/engine/cvar_system.i: src/engine/cvar_system.cpp.i
.PHONY : src/engine/cvar_system.i

# target to preprocess a source file
src/engine/cvar_system.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_engine.dir/build.make CMakeFiles/zq_engine.dir/src/engine/cvar_system.cpp.i
.PHONY : src/engine/cvar_system.cpp.i

src/engine/cvar_system.s: src/engine/cvar_system.cpp.s
.PHONY : src/engine/cvar_system.s

# target to generate assembly for a file
src/engine/cvar_system.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_engine.dir/build.make CMakeFiles/zq_engine.dir/src/engine/cvar_system.cpp.s
.PHONY : src/engine/cvar_system.cpp.s

src/engine/entity.o: src/engine/entity.cpp.o
.PHONY : src/engine/entity.o

# target to build an object file
src/engine/entity.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_engine.dir/build.make CMakeFiles/zq_engine.dir/src/engine/entity.cpp.o
.PHONY : src/engine/entity.cpp.o

src/engine/entity.i: src/engine/entity.cpp.i
.PHONY : src/engine/entity.i

# target to preprocess a source file
src/engine/entity.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_engine.dir/build.make CMakeFiles/zq_engine.dir/src/engine/entity.cpp.i
.PHONY : src/engine/entity.cpp.i

src/engine/entity.s: src/engine/entity.cpp.s
.PHONY : src/engine/entity.s

# target to generate assembly for a file
src/engine/entity.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_engine.dir/build.make CMakeFiles/zq_engine.dir/src/engine/entity.cpp.s
.PHONY : src/engine/entity.cpp.s

src/engine/game.o: src/engine/game.cpp.o
.PHONY : src/engine/game.o

# target to build an object file
src/engine/game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_engine.dir/build.make CMakeFiles/zq_engine.dir/src/engine/game.cpp.o
.PHONY : src/engine/game.cpp.o

src/engine/game.i: src/engine/game.cpp.i
.PHONY : src/engine/game.i

# target to preprocess a source file
src/engine/game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_engine.dir/build.make CMakeFiles/zq_engine.dir/src/engine/game.cpp.i
.PHONY : src/engine/game.cpp.i

src/engine/game.s: src/engine/game.cpp.s
.PHONY : src/engine/game.s

# target to generate assembly for a file
src/engine/game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_engine.dir/build.make CMakeFiles/zq_engine.dir/src/engine/game.cpp.s
.PHONY : src/engine/game.cpp.s

src/engine/game_builtins.o: src/engine/game_builtins.cpp.o
.PHONY : src/engine/game_builtins.o

# target to build an object file
src/engine/game_builtins.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_engine.dir/build.make CMakeFiles/zq_engine.dir/src/engine/game_builtins.cpp.o
.PHONY : src/engine/game_builtins.cpp.o

src/engine/game_builtins.i: src/engine/game_builtins.cpp.i
.PHONY : src/engine/game_builtins.i

# target to preprocess a source file
src/engine/game_builtins.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_engine.dir/build.make CMakeFiles/zq_engine.dir/src/engine/game_builtins.cpp.i
.PHONY : src/engine/game_builtins.cpp.i

src/engine/game_builtins.s: src/engine/game_builtins.cpp.s
.PHONY : src/engine/game_builtins.s

# target to generate assembly for a file
src/engine/game_builtins.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_engine.dir/build.make CMakeFiles/zq_engine.dir/src/engine/game_builtins.cpp.s
.PHONY : src/engine/game_builtins.cpp.s

src/engine/gameframe.o: src/engine/gameframe.cpp.o
.PHONY : src/engine/gameframe.o

# target to build an object file
src/engine/gameframe.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_engine.dir/build.make CMakeFiles/zq_engine.dir/src/engine/gameframe.cpp.o
.PHONY : src/engine/gameframe.cpp.o

src/engine/gameframe.i: src/engine/gameframe.cpp.i
.PHONY : src/engine/gameframe.i

# target to preprocess a source file
src/engine/gameframe.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_engine.dir/build.make CMakeFiles/zq_engine.dir/src/engine/gameframe.cpp.i
.PHONY : src/engine/gameframe.cpp.i

src/engine/gameframe.s: src/engine/gameframe.cpp.s
.PHONY : src/engine/gameframe.s

# target to generate assembly for a file
src/engine/gameframe.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_engine.dir/build.make CMakeFiles/zq_engine.dir/src/engine/gameframe.cpp.s
.PHONY : src/engine/gameframe.cpp.s

src/engine/host.o: src/engine/host.cpp.o
.PHONY : src/engine/host.o

# target to build an object file
src/engine/host.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_engine.dir/build.make CMakeFiles/zq_engine.dir/src/engine/host.cpp.o
.PHONY : src/engine/host.cpp.o

src/engine/host.i: src/engine/host.cpp.i
.PHONY : src/engine/host.i

# target to preprocess a source file
src/engine/host.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_engine.dir/build.make CMakeFiles/zq_engine.dir/src/engine/host.cpp.i
.PHONY : src/engine/host.cpp.i

src/engine/host.s: src/engine/host.cpp.s
.PHONY : src/engine/host.s

# target to generate assembly for a file
src/engine/host.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_engine.dir/build.make CMakeFiles/zq_engine.dir/src/engine/host.cpp.s
.PHONY : src/engine/host.cpp.s

src/engine/input.o: src/engine/input.cpp.o
.PHONY : src/engine/input.o

# target to build an object file
src/engine/input.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_engine.dir/build.make CMakeFiles/zq_engine.dir/src/engine/input.cpp.o
.PHONY : src/engine/input.cpp.o

src/engine/input.i: src/engine/input.cpp.i
.PHONY : src/engine/input.i

# target to preprocess a source file
src/engine/input.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_engine.dir/build.make CMakeFiles/zq_engine.dir/src/engine/input.cpp.i
.PHONY : src/engine/input.cpp.i

src/engine/input.s: src/engine/input.cpp.s
.PHONY : src/engine/input.s

# target to generate assembly for a file
src/engine/input.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_engine.dir/build.make CMakeFiles/zq_engine.dir/src/engine/input.cpp.s
.PHONY : src/engine/input.cpp.s

src/engine/mdl_model.o: src/engine/mdl_model.cpp.o
.PHONY : src/engine/mdl_model.o

# target to build an object file
src/engine/mdl_model.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_engine.dir/build.make CMakeFiles/zq_engine.dir/src/engine/mdl_model.cpp.o
.PHONY : src/engine/mdl_model.cpp.o

src/engine/mdl_model.i: src/engine/mdl_model.cpp.i
.PHONY : src/engine/mdl_model.i

# target to preprocess a source file
src/engine/mdl_model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_engine.dir/build.make CMakeFiles/zq_engine.dir/src/engine/mdl_model.cpp.i
.PHONY : src/engine/mdl_model.cpp.i

src/engine/mdl_model.s: src/engine/mdl_model.cpp.s
.PHONY : src/engine/mdl_model.s

# target to generate assembly for a file
src/engine/mdl_model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_engine.dir/build.make CMakeFiles/zq_engine.dir/src/engine/mdl_model.cpp.s
.PHONY : src/engine/mdl_model.cpp.s

src/engine/model.o: src/engine/model.cpp.o
.PHONY : src/engine/model.o

# target to build an object file
src/engine/model.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_engine.dir/build.make CMakeFiles/zq_engine.dir/src/engine/model.cpp.o
.PHONY : src/engine/model.cpp.o

src/engine/model.i: src/engine/model.cpp.i
.PHONY : src/engine/model.i

# target to preprocess a source file
src/engine/model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_engine.dir/build.make CMakeFiles/zq_engine.dir/src/engine/model.cpp.i
.PHONY : src/engine/model.cpp.i

src/engine/model.s: src/engine/model.cpp.s
.PHONY : src/engine/model.s

# target to generate assembly for a file
src/engine/model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_engine.dir/build.make CMakeFiles/zq_engine.dir/src/engine/model.cpp.s
.PHONY : src/engine/model.cpp.s

src/engine/monster_move.o: src/engine/monster_move.cpp.o
.PHONY : src/engine/monster_move.o

# target to build an object file
src/engine/monster_move.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_engine.dir/build.make CMakeFiles/zq_engine.dir/src/engine/monster_move.cpp.o
.PHONY : src/engine/monster_move.cpp.o

src/engine/monster_move.i: src/engine/monster_move.cpp.i
.PHONY : src/engine/monster_move.i

# target to preprocess a source file
src/engine/monster_move.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_engine.dir/build.make CMakeFiles/zq_engine.dir/src/engine/monster_move.cpp.i
.PHONY : src/engine/monster_move.cpp.i

src/engine/monster_move.s: src/engine/monster_move.cpp.s
.PHONY : src/engine/monster_move.s

# target to generate assembly for a file
src/engine/monster_move.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_engine.dir/build.make CMakeFiles/zq_engine.dir/src/engine/monster_move.cpp.s
.PHONY : src/engine/monster_move.cpp.s

src/engine/move.o: src/engine/move.cpp.o
.PHONY : src/engine/move.o

# target to build an object file
src/engine/move.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_engine.dir/build.make CMakeFiles/zq_engine.dir/src/engine/move.cpp.o
.PHONY : src/engine/move.cpp.o

src/engine/move.i: src/engine/move.cpp.i
.PHONY : src/engine/move.i

# target to preprocess a source file
src/engine/move.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_engine.dir/build.make CMakeFiles/zq_engine.dir/src/engine/move.cpp.i
.PHONY : src/engine/move.cpp.i

src/engine/move.s: src/engine/move.cpp.s
.PHONY : src/engine/move.s

# target to generate assembly for a file
src/engine/move.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_engine.dir/build.make CMakeFiles/zq_engine.dir/src/engine/move.cpp.s
.PHONY : src/engine/move.cpp.s

src/engine/particle.o: src/engine/particle.cpp.o
.PHONY : src/engine/particle.o

# target to build an object file
src/engine/particle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_engine.dir/build.make CMakeFiles/zq_engine.dir/src/engine/particle.cpp.o
.PHONY : src/engine/particle.cpp.o

src/engine/particle.i: src/engine/particle.cpp.i
.PHONY : src/engine/particle.i

# target to preprocess a source file
src/engine/particle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_engine.dir/build.make CMakeFiles/zq_engine.dir/src/engine/particle.cpp.i
.PHONY : src/engine/particle.cpp.i

src/engine/particle.s: src/engine/particle.cpp.s
.PHONY : src/engine/particle.s

# target to generate assembly for a file
src/engine/particle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_engine.dir/build.make CMakeFiles/zq_engine.dir/src/engine/particle.cpp.s
.PHONY : src/engine/particle.cpp.s

src/engine/world.o: src/engine/world.cpp.o
.PHONY : src/engine/world.o

# target to build an object file
src/engine/world.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_engine.dir/build.make CMakeFiles/zq_engine.dir/src/engine/world.cpp.o
.PHONY : src/engine/world.cpp.o

src/engine/world.i: src/engine/world.cpp.i
.PHONY : src/engine/world.i

# target to preprocess a source file
src/engine/world.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_engine.dir/build.make CMakeFiles/zq_engine.dir/src/engine/world.cpp.i
.PHONY : src/engine/world.cpp.i

src/engine/world.s: src/engine/world.cpp.s
.PHONY : src/engine/world.s

# target to generate assembly for a file
src/engine/world.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_engine.dir/build.make CMakeFiles/zq_engine.dir/src/engine/world.cpp.s
.PHONY : src/engine/world.cpp.s

src/filesystem/pak_archive.o: src/filesystem/pak_archive.cpp.o
.PHONY : src/filesystem/pak_archive.o

# target to build an object file
src/filesystem/pak_archive.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_filesystem.dir/build.make CMakeFiles/zq_filesystem.dir/src/filesystem/pak_archive.cpp.o
.PHONY : src/filesystem/pak_archive.cpp.o

src/filesystem/pak_archive.i: src/filesystem/pak_archive.cpp.i
.PHONY : src/filesystem/pak_archive.i

# target to preprocess a source file
src/filesystem/pak_archive.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_filesystem.dir/build.make CMakeFiles/zq_filesystem.dir/src/filesystem/pak_archive.cpp.i
.PHONY : src/filesystem/pak_archive.cpp.i

src/filesystem/pak_archive.s: src/filesystem/pak_archive.cpp.s
.PHONY : src/filesystem/pak_archive.s

# target to generate assembly for a file
src/filesystem/pak_archive.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_filesystem.dir/build.make CMakeFiles/zq_filesystem.dir/src/filesystem/pak_archive.cpp.s
.PHONY : src/filesystem/pak_archive.cpp.s

src/filesystem/path_util.o: src/filesystem/path_util.cpp.o
.PHONY : src/filesystem/path_util.o

# target to build an object file
src/filesystem/path_util.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_filesystem.dir/build.make CMakeFiles/zq_filesystem.dir/src/filesystem/path_util.cpp.o
.PHONY : src/filesystem/path_util.cpp.o

src/filesystem/path_util.i: src/filesystem/path_util.cpp.i
.PHONY : src/filesystem/path_util.i

# target to preprocess a source file
src/filesystem/path_util.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_filesystem.dir/build.make CMakeFiles/zq_filesystem.dir/src/filesystem/path_util.cpp.i
.PHONY : src/filesystem/path_util.cpp.i

src/filesystem/path_util.s: src/filesystem/path_util.cpp.s
.PHONY : src/filesystem/path_util.s

# target to generate assembly for a file
src/filesystem/path_util.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_filesystem.dir/build.make CMakeFiles/zq_filesystem.dir/src/filesystem/path_util.cpp.s
.PHONY : src/filesystem/path_util.cpp.s

src/filesystem/virtual_fs.o: src/filesystem/virtual_fs.cpp.o
.PHONY : src/filesystem/virtual_fs.o

# target to build an object file
src/filesystem/virtual_fs.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_filesystem.dir/build.make CMakeFiles/zq_filesystem.dir/src/filesystem/virtual_fs.cpp.o
.PHONY : src/filesystem/virtual_fs.cpp.o

src/filesystem/virtual_fs.i: src/filesystem/virtual_fs.cpp.i
.PHONY : src/filesystem/virtual_fs.i

# target to preprocess a source file
src/filesystem/virtual_fs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_filesystem.dir/build.make CMakeFiles/zq_filesystem.dir/src/filesystem/virtual_fs.cpp.i
.PHONY : src/filesystem/virtual_fs.cpp.i

src/filesystem/virtual_fs.s: src/filesystem/virtual_fs.cpp.s
.PHONY : src/filesystem/virtual_fs.s

# target to generate assembly for a file
src/filesystem/virtual_fs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_filesystem.dir/build.make CMakeFiles/zq_filesystem.dir/src/filesystem/virtual_fs.cpp.s
.PHONY : src/filesystem/virtual_fs.cpp.s

src/render/font8x8.o: src/render/font8x8.cpp.o
.PHONY : src/render/font8x8.o

# target to build an object file
src/render/font8x8.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_render.dir/build.make CMakeFiles/zq_render.dir/src/render/font8x8.cpp.o
.PHONY : src/render/font8x8.cpp.o

src/render/font8x8.i: src/render/font8x8.cpp.i
.PHONY : src/render/font8x8.i

# target to preprocess a source file
src/render/font8x8.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_render.dir/build.make CMakeFiles/zq_render.dir/src/render/font8x8.cpp.i
.PHONY : src/render/font8x8.cpp.i

src/render/font8x8.s: src/render/font8x8.cpp.s
.PHONY : src/render/font8x8.s

# target to generate assembly for a file
src/render/font8x8.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_render.dir/build.make CMakeFiles/zq_render.dir/src/render/font8x8.cpp.s
.PHONY : src/render/font8x8.cpp.s

src/render/ray_scene.o: src/render/ray_scene.cpp.o
.PHONY : src/render/ray_scene.o

# target to build an object file
src/render/ray_scene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_render.dir/build.make CMakeFiles/zq_render.dir/src/render/ray_scene.cpp.o
.PHONY : src/render/ray_scene.cpp.o

src/render/ray_scene.i: src/render/ray_scene.cpp.i
.PHONY : src/render/ray_scene.i

# target to preprocess a source file
src/render/ray_scene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_render.dir/build.make CMakeFiles/zq_render.dir/src/render/ray_scene.cpp.i
.PHONY : src/render/ray_scene.cpp.i

src/render/ray_scene.s: src/render/ray_scene.cpp.s
.PHONY : src/render/ray_scene.s

# target to generate assembly for a file
src/render/ray_scene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_render.dir/build.make CMakeFiles/zq_render.dir/src/render/ray_scene.cpp.s
.PHONY : src/render/ray_scene.cpp.s

src/render/raytracer.o: src/render/raytracer.cpp.o
.PHONY : src/render/raytracer.o

# target to build an object file
src/render/raytracer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_render.dir/build.make CMakeFiles/zq_render.dir/src/render/raytracer.cpp.o
.PHONY : src/render/raytracer.cpp.o

src/render/raytracer.i: src/render/raytracer.cpp.i
.PHONY : src/render/raytracer.i

# target to preprocess a source file
src/render/raytracer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_render.dir/build.make CMakeFiles/zq_render.dir/src/render/raytracer.cpp.i
.PHONY : src/render/raytracer.cpp.i

src/render/raytracer.s: src/render/raytracer.cpp.s
.PHONY : src/render/raytracer.s

# target to generate assembly for a file
src/render/raytracer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_render.dir/build.make CMakeFiles/zq_render.dir/src/render/raytracer.cpp.s
.PHONY : src/render/raytracer.cpp.s

src/render/software_renderer.o: src/render/software_renderer.cpp.o
.PHONY : src/render/software_renderer.o

# target to build an object file
src/render/software_renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_render.dir/build.make CMakeFiles/zq_render.dir/src/render/software_renderer.cpp.o
.PHONY : src/render/software_renderer.cpp.o

src/render/software_renderer.i: src/render/software_renderer.cpp.i
.PHONY : src/render/software_renderer.i

# target to preprocess a source file
src/render/software_renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_render.dir/build.make CMakeFiles/zq_render.dir/src/render/software_renderer.cpp.i
.PHONY : src/render/software_renderer.cpp.i

src/render/software_renderer.s: src/render/software_renderer.cpp.s
.PHONY : src/render/software_renderer.s

# target to generate assembly for a file
src/render/software_renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_render.dir/build.make CMakeFiles/zq_render.dir/src/render/software_renderer.cpp.s
.PHONY : src/render/software_renderer.cpp.s

src/subsystems/client.o: src/subsystems/client.cpp.o
.PHONY : src/subsystems/client.o

# target to build an object file
src/subsystems/client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_subsystems.dir/build.make CMakeFiles/zq_subsystems.dir/src/subsystems/client.cpp.o
.PHONY : src/subsystems/client.cpp.o

src/subsystems/client.i: src/subsystems/client.cpp.i
.PHONY : src/subsystems/client.i

# target to preprocess a source file
src/subsystems/client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_subsystems.dir/build.make CMakeFiles/zq_subsystems.dir/src/subsystems/client.cpp.i
.PHONY : src/subsystems/client.cpp.i

src/subsystems/client.s: src/subsystems/client.cpp.s
.PHONY : src/subsystems/client.s

# target to generate assembly for a file
src/subsystems/client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_subsystems.dir/build.make CMakeFiles/zq_subsystems.dir/src/subsystems/client.cpp.s
.PHONY : src/subsystems/client.cpp.s

src/subsystems/net_addr.o: src/subsystems/net_addr.cpp.o
.PHONY : src/subsystems/net_addr.o

# target to build an object file
src/subsystems/net_addr.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_subsystems.dir/build.make CMakeFiles/zq_subsystems.dir/src/subsystems/net_addr.cpp.o
.PHONY : src/subsystems/net_addr.cpp.o

src/subsystems/net_addr.i: src/subsystems/net_addr.cpp.i
.PHONY : src/subsystems/net_addr.i

# target to preprocess a source file
src/subsystems/net_addr.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_subsystems.dir/build.make CMakeFiles/zq_subsystems.dir/src/subsystems/net_addr.cpp.i
.PHONY : src/subsystems/net_addr.cpp.i

src/subsystems/net_addr.s: src/subsystems/net_addr.cpp.s
.PHONY : src/subsystems/net_addr.s

# target to generate assembly for a file
src/subsystems/net_addr.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_subsystems.dir/build.make CMakeFiles/zq_subsystems.dir/src/subsystems/net_addr.cpp.s
.PHONY : src/subsystems/net_addr.cpp.s

src/subsystems/net_driver.o: src/subsystems/net_driver.cpp.o
.PHONY : src/subsystems/net_driver.o

# target to build an object file
src/subsystems/net_driver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_subsystems.dir/build.make CMakeFiles/zq_subsystems.dir/src/subsystems/net_driver.cpp.o
.PHONY : src/subsystems/net_driver.cpp.o

src/subsystems/net_driver.i: src/subsystems/net_driver.cpp.i
.PHONY : src/subsystems/net_driver.i

# target to preprocess a source file
src/subsystems/net_driver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_subsystems.dir/build.make CMakeFiles/zq_subsystems.dir/src/subsystems/net_driver.cpp.i
.PHONY : src/subsystems/net_driver.cpp.i

src/subsystems/net_driver.s: src/subsystems/net_driver.cpp.s
.PHONY : src/subsystems/net_driver.s

# target to generate assembly for a file
src/subsystems/net_driver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_subsystems.dir/build.make CMakeFiles/zq_subsystems.dir/src/subsystems/net_driver.cpp.s
.PHONY : src/subsystems/net_driver.cpp.s

src/subsystems/protocol.o: src/subsystems/protocol.cpp.o
.PHONY : src/subsystems/protocol.o

# target to build an object file
src/subsystems/protocol.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_subsystems.dir/build.make CMakeFiles/zq_subsystems.dir/src/subsystems/protocol.cpp.o
.PHONY : src/subsystems/protocol.cpp.o

src/subsystems/protocol.i: src/subsystems/protocol.cpp.i
.PHONY : src/subsystems/protocol.i

# target to preprocess a source file
src/subsystems/protocol.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_subsystems.dir/build.make CMakeFiles/zq_subsystems.dir/src/subsystems/protocol.cpp.i
.PHONY : src/subsystems/protocol.cpp.i

src/subsystems/protocol.s: src/subsystems/protocol.cpp.s
.PHONY : src/subsystems/protocol.s

# target to generate assembly for a file
src/subsystems/protocol.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_subsystems.dir/build.make CMakeFiles/zq_subsystems.dir/src/subsystems/protocol.cpp.s
.PHONY : src/subsystems/protocol.cpp.s

src/subsystems/reliable_channel.o: src/subsystems/reliable_channel.cpp.o
.PHONY : src/subsystems/reliable_channel.o

# target to build an object file
src/subsystems/reliable_channel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_subsystems.dir/build.make CMakeFiles/zq_subsystems.dir/src/subsystems/reliable_channel.cpp.o
.PHONY : src/subsystems/reliable_channel.cpp.o

src/subsystems/reliable_channel.i: src/subsystems/reliable_channel.cpp.i
.PHONY : src/subsystems/reliable_channel.i

# target to preprocess a source file
src/subsystems/reliable_channel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_subsystems.dir/build.make CMakeFiles/zq_subsystems.dir/src/subsystems/reliable_channel.cpp.i
.PHONY : src/subsystems/reliable_channel.cpp.i

src/subsystems/reliable_channel.s: src/subsystems/reliable_channel.cpp.s
.PHONY : src/subsystems/reliable_channel.s

# target to generate assembly for a file
src/subsystems/reliable_channel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_subsystems.dir/build.make CMakeFiles/zq_subsystems.dir/src/subsystems/reliable_channel.cpp.s
.PHONY : src/subsystems/reliable_channel.cpp.s

src/subsystems/server.o: src/subsystems/server.cpp.o
.PHONY : src/subsystems/server.o

# target to build an object file
src/subsystems/server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_subsystems.dir/build.make CMakeFiles/zq_subsystems.dir/src/subsystems/server.cpp.o
.PHONY : src/subsystems/server.cpp.o

src/subsystems/server.i: src/subsystems/server.cpp.i
.PHONY : src/subsystems/server.i

# target to preprocess a source file
src/subsystems/server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_subsystems.dir/build.make CMakeFiles/zq_subsystems.dir/src/subsystems/server.cpp.i
.PHONY : src/subsystems/server.cpp.i

src/subsystems/server.s: src/subsystems/server.cpp.s
.PHONY : src/subsystems/server.s

# target to generate assembly for a file
src/subsystems/server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_subsystems.dir/build.make CMakeFiles/zq_subsystems.dir/src/subsystems/server.cpp.s
.PHONY : src/subsystems/server.cpp.s

src/vm/builtin_registry.o: src/vm/builtin_registry.cpp.o
.PHONY : src/vm/builtin_registry.o

# target to build an object file
src/vm/builtin_registry.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_vm.dir/build.make CMakeFiles/zq_vm.dir/src/vm/builtin_registry.cpp.o
.PHONY : src/vm/builtin_registry.cpp.o

src/vm/builtin_registry.i: src/vm/builtin_registry.cpp.i
.PHONY : src/vm/builtin_registry.i

# target to preprocess a source file
src/vm/builtin_registry.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_vm.dir/build.make CMakeFiles/zq_vm.dir/src/vm/builtin_registry.cpp.i
.PHONY : src/vm/builtin_registry.cpp.i

src/vm/builtin_registry.s: src/vm/builtin_registry.cpp.s
.PHONY : src/vm/builtin_registry.s

# target to generate assembly for a file
src/vm/builtin_registry.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_vm.dir/build.make CMakeFiles/zq_vm.dir/src/vm/builtin_registry.cpp.s
.PHONY : src/vm/builtin_registry.cpp.s

src/vm/bytecode.o: src/vm/bytecode.cpp.o
.PHONY : src/vm/bytecode.o

# target to build an object file
src/vm/bytecode.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_vm.dir/build.make CMakeFiles/zq_vm.dir/src/vm/bytecode.cpp.o
.PHONY : src/vm/bytecode.cpp.o

src/vm/bytecode.i: src/vm/bytecode.cpp.i
.PHONY : src/vm/bytecode.i

# target to preprocess a source file
src/vm/bytecode.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_vm.dir/build.make CMakeFiles/zq_vm.dir/src/vm/bytecode.cpp.i
.PHONY : src/vm/bytecode.cpp.i

src/vm/bytecode.s: src/vm/bytecode.cpp.s
.PHONY : src/vm/bytecode.s

# target to generate assembly for a file
src/vm/bytecode.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_vm.dir/build.make CMakeFiles/zq_vm.dir/src/vm/bytecode.cpp.s
.PHONY : src/vm/bytecode.cpp.s

src/vm/libstd/cl_parse.o: src/vm/libstd/cl_parse.cpp.o
.PHONY : src/vm/libstd/cl_parse.o

# target to build an object file
src/vm/libstd/cl_parse.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_vm.dir/build.make CMakeFiles/zq_vm.dir/src/vm/libstd/cl_parse.cpp.o
.PHONY : src/vm/libstd/cl_parse.cpp.o

src/vm/libstd/cl_parse.i: src/vm/libstd/cl_parse.cpp.i
.PHONY : src/vm/libstd/cl_parse.i

# target to preprocess a source file
src/vm/libstd/cl_parse.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_vm.dir/build.make CMakeFiles/zq_vm.dir/src/vm/libstd/cl_parse.cpp.i
.PHONY : src/vm/libstd/cl_parse.cpp.i

src/vm/libstd/cl_parse.s: src/vm/libstd/cl_parse.cpp.s
.PHONY : src/vm/libstd/cl_parse.s

# target to generate assembly for a file
src/vm/libstd/cl_parse.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_vm.dir/build.make CMakeFiles/zq_vm.dir/src/vm/libstd/cl_parse.cpp.s
.PHONY : src/vm/libstd/cl_parse.cpp.s

src/vm/libstd/pr_edict.o: src/vm/libstd/pr_edict.cpp.o
.PHONY : src/vm/libstd/pr_edict.o

# target to build an object file
src/vm/libstd/pr_edict.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_vm.dir/build.make CMakeFiles/zq_vm.dir/src/vm/libstd/pr_edict.cpp.o
.PHONY : src/vm/libstd/pr_edict.cpp.o

src/vm/libstd/pr_edict.i: src/vm/libstd/pr_edict.cpp.i
.PHONY : src/vm/libstd/pr_edict.i

# target to preprocess a source file
src/vm/libstd/pr_edict.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_vm.dir/build.make CMakeFiles/zq_vm.dir/src/vm/libstd/pr_edict.cpp.i
.PHONY : src/vm/libstd/pr_edict.cpp.i

src/vm/libstd/pr_edict.s: src/vm/libstd/pr_edict.cpp.s
.PHONY : src/vm/libstd/pr_edict.s

# target to generate assembly for a file
src/vm/libstd/pr_edict.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_vm.dir/build.make CMakeFiles/zq_vm.dir/src/vm/libstd/pr_edict.cpp.s
.PHONY : src/vm/libstd/pr_edict.cpp.s

src/vm/libstd/sv_globals.o: src/vm/libstd/sv_globals.cpp.o
.PHONY : src/vm/libstd/sv_globals.o

# target to build an object file
src/vm/libstd/sv_globals.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_vm.dir/build.make CMakeFiles/zq_vm.dir/src/vm/libstd/sv_globals.cpp.o
.PHONY : src/vm/libstd/sv_globals.cpp.o

src/vm/libstd/sv_globals.i: src/vm/libstd/sv_globals.cpp.i
.PHONY : src/vm/libstd/sv_globals.i

# target to preprocess a source file
src/vm/libstd/sv_globals.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_vm.dir/build.make CMakeFiles/zq_vm.dir/src/vm/libstd/sv_globals.cpp.i
.PHONY : src/vm/libstd/sv_globals.cpp.i

src/vm/libstd/sv_globals.s: src/vm/libstd/sv_globals.cpp.s
.PHONY : src/vm/libstd/sv_globals.s

# target to generate assembly for a file
src/vm/libstd/sv_globals.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_vm.dir/build.make CMakeFiles/zq_vm.dir/src/vm/libstd/sv_globals.cpp.s
.PHONY : src/vm/libstd/sv_globals.cpp.s

src/vm/opcode.o: src/vm/opcode.cpp.o
.PHONY : src/vm/opcode.o

# target to build an object file
src/vm/opcode.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_vm.dir/build.make CMakeFiles/zq_vm.dir/src/vm/opcode.cpp.o
.PHONY : src/vm/opcode.cpp.o

src/vm/opcode.i: src/vm/opcode.cpp.i
.PHONY : src/vm/opcode.i

# target to preprocess a source file
src/vm/opcode.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_vm.dir/build.make CMakeFiles/zq_vm.dir/src/vm/opcode.cpp.i
.PHONY : src/vm/opcode.cpp.i

src/vm/opcode.s: src/vm/opcode.cpp.s
.PHONY : src/vm/opcode.s

# target to generate assembly for a file
src/vm/opcode.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_vm.dir/build.make CMakeFiles/zq_vm.dir/src/vm/opcode.cpp.s
.PHONY : src/vm/opcode.cpp.s

src/vm/prog_builtins.o: src/vm/prog_builtins.cpp.o
.PHONY : src/vm/prog_builtins.o

# target to build an object file
src/vm/prog_builtins.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_vm.dir/build.make CMakeFiles/zq_vm.dir/src/vm/prog_builtins.cpp.o
.PHONY : src/vm/prog_builtins.cpp.o

src/vm/prog_builtins.i: src/vm/prog_builtins.cpp.i
.PHONY : src/vm/prog_builtins.i

# target to preprocess a source file
src/vm/prog_builtins.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_vm.dir/build.make CMakeFiles/zq_vm.dir/src/vm/prog_builtins.cpp.i
.PHONY : src/vm/prog_builtins.cpp.i

src/vm/prog_builtins.s: src/vm/prog_builtins.cpp.s
.PHONY : src/vm/prog_builtins.s

# target to generate assembly for a file
src/vm/prog_builtins.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_vm.dir/build.make CMakeFiles/zq_vm.dir/src/vm/prog_builtins.cpp.s
.PHONY : src/vm/prog_builtins.cpp.s

src/vm/prog_vm.o: src/vm/prog_vm.cpp.o
.PHONY : src/vm/prog_vm.o

# target to build an object file
src/vm/prog_vm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_vm.dir/build.make CMakeFiles/zq_vm.dir/src/vm/prog_vm.cpp.o
.PHONY : src/vm/prog_vm.cpp.o

src/vm/prog_vm.i: src/vm/prog_vm.cpp.i
.PHONY : src/vm/prog_vm.i

# target to preprocess a source file
src/vm/prog_vm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_vm.dir/build.make CMakeFiles/zq_vm.dir/src/vm/prog_vm.cpp.i
.PHONY : src/vm/prog_vm.cpp.i

src/vm/prog_vm.s: src/vm/prog_vm.cpp.s
.PHONY : src/vm/prog_vm.s

# target to generate assembly for a file
src/vm/prog_vm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_vm.dir/build.make CMakeFiles/zq_vm.dir/src/vm/prog_vm.cpp.s
.PHONY : src/vm/prog_vm.cpp.s

src/vm/vm.o: src/vm/vm.cpp.o
.PHONY : src/vm/vm.o

# target to build an object file
src/vm/vm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_vm.dir/build.make CMakeFiles/zq_vm.dir/src/vm/vm.cpp.o
.PHONY : src/vm/vm.cpp.o

src/vm/vm.i: src/vm/vm.cpp.i
.PHONY : src/vm/vm.i

# target to preprocess a source file
src/vm/vm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_vm.dir/build.make CMakeFiles/zq_vm.dir/src/vm/vm.cpp.i
.PHONY : src/vm/vm.cpp.i

src/vm/vm.s: src/vm/vm.cpp.s
.PHONY : src/vm/vm.s

# target to generate assembly for a file
src/vm/vm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_vm.dir/build.make CMakeFiles/zq_vm.dir/src/vm/vm.cpp.s
.PHONY : src/vm/vm.cpp.s

src/vulkan/command_pool.o: src/vulkan/command_pool.cpp.o
.PHONY : src/vulkan/command_pool.o

# target to build an object file
src/vulkan/command_pool.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_vulkan.dir/build.make CMakeFiles/zq_vulkan.dir/src/vulkan/command_pool.cpp.o
.PHONY : src/vulkan/command_pool.cpp.o

src/vulkan/command_pool.i: src/vulkan/command_pool.cpp.i
.PHONY : src/vulkan/command_pool.i

# target to preprocess a source file
src/vulkan/command_pool.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_vulkan.dir/build.make CMakeFiles/zq_vulkan.dir/src/vulkan/command_pool.cpp.i
.PHONY : src/vulkan/command_pool.cpp.i

src/vulkan/command_pool.s: src/vulkan/command_pool.cpp.s
.PHONY : src/vulkan/command_pool.s

# target to generate assembly for a file
src/vulkan/command_pool.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_vulkan.dir/build.make CMakeFiles/zq_vulkan.dir/src/vulkan/command_pool.cpp.s
.PHONY : src/vulkan/command_pool.cpp.s

src/vulkan/render_command.o: src/vulkan/render_command.cpp.o
.PHONY : src/vulkan/render_command.o

# target to build an object file
src/vulkan/render_command.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_vulkan.dir/build.make CMakeFiles/zq_vulkan.dir/src/vulkan/render_command.cpp.o
.PHONY : src/vulkan/render_command.cpp.o

src/vulkan/render_command.i: src/vulkan/render_command.cpp.i
.PHONY : src/vulkan/render_command.i

# target to preprocess a source file
src/vulkan/render_command.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_vulkan.dir/build.make CMakeFiles/zq_vulkan.dir/src/vulkan/render_command.cpp.i
.PHONY : src/vulkan/render_command.cpp.i

src/vulkan/render_command.s: src/vulkan/render_command.cpp.s
.PHONY : src/vulkan/render_command.s

# target to generate assembly for a file
src/vulkan/render_command.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_vulkan.dir/build.make CMakeFiles/zq_vulkan.dir/src/vulkan/render_command.cpp.s
.PHONY : src/vulkan/render_command.cpp.s

src/vulkan/render_thread.o: src/vulkan/render_thread.cpp.o
.PHONY : src/vulkan/render_thread.o

# target to build an object file
src/vulkan/render_thread.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_vulkan.dir/build.make CMakeFiles/zq_vulkan.dir/src/vulkan/render_thread.cpp.o
.PHONY : src/vulkan/render_thread.cpp.o

src/vulkan/render_thread.i: src/vulkan/render_thread.cpp.i
.PHONY : src/vulkan/render_thread.i

# target to preprocess a source file
src/vulkan/render_thread.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_vulkan.dir/build.make CMakeFiles/zq_vulkan.dir/src/vulkan/render_thread.cpp.i
.PHONY : src/vulkan/render_thread.cpp.i

src/vulkan/render_thread.s: src/vulkan/render_thread.cpp.s
.PHONY : src/vulkan/render_thread.s

# target to generate assembly for a file
src/vulkan/render_thread.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_vulkan.dir/build.make CMakeFiles/zq_vulkan.dir/src/vulkan/render_thread.cpp.s
.PHONY : src/vulkan/render_thread.cpp.s

src/vulkan/vulkan_api.o: src/vulkan/vulkan_api.cpp.o
.PHONY : src/vulkan/vulkan_api.o

# target to build an object file
src/vulkan/vulkan_api.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_vulkan.dir/build.make CMakeFiles/zq_vulkan.dir/src/vulkan/vulkan_api.cpp.o
.PHONY : src/vulkan/vulkan_api.cpp.o

src/vulkan/vulkan_api.i: src/vulkan/vulkan_api.cpp.i
.PHONY : src/vulkan/vulkan_api.i

# target to preprocess a source file
src/vulkan/vulkan_api.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_vulkan.dir/build.make CMakeFiles/zq_vulkan.dir/src/vulkan/vulkan_api.cpp.i
.PHONY : src/vulkan/vulkan_api.cpp.i

src/vulkan/vulkan_api.s: src/vulkan/vulkan_api.cpp.s
.PHONY : src/vulkan/vulkan_api.s

# target to generate assembly for a file
src/vulkan/vulkan_api.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_vulkan.dir/build.make CMakeFiles/zq_vulkan.dir/src/vulkan/vulkan_api.cpp.s
.PHONY : src/vulkan/vulkan_api.cpp.s

src/vulkan/vulkan_buffer.o: src/vulkan/vulkan_buffer.cpp.o
.PHONY : src/vulkan/vulkan_buffer.o

# target to build an object file
src/vulkan/vulkan_buffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_vulkan.dir/build.make CMakeFiles/zq_vulkan.dir/src/vulkan/vulkan_buffer.cpp.o
.PHONY : src/vulkan/vulkan_buffer.cpp.o

src/vulkan/vulkan_buffer.i: src/vulkan/vulkan_buffer.cpp.i
.PHONY : src/vulkan/vulkan_buffer.i

# target to preprocess a source file
src/vulkan/vulkan_buffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_vulkan.dir/build.make CMakeFiles/zq_vulkan.dir/src/vulkan/vulkan_buffer.cpp.i
.PHONY : src/vulkan/vulkan_buffer.cpp.i

src/vulkan/vulkan_buffer.s: src/vulkan/vulkan_buffer.cpp.s
.PHONY : src/vulkan/vulkan_buffer.s

# target to generate assembly for a file
src/vulkan/vulkan_buffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_vulkan.dir/build.make CMakeFiles/zq_vulkan.dir/src/vulkan/vulkan_buffer.cpp.s
.PHONY : src/vulkan/vulkan_buffer.cpp.s

src/vulkan/vulkan_image.o: src/vulkan/vulkan_image.cpp.o
.PHONY : src/vulkan/vulkan_image.o

# target to build an object file
src/vulkan/vulkan_image.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_vulkan.dir/build.make CMakeFiles/zq_vulkan.dir/src/vulkan/vulkan_image.cpp.o
.PHONY : src/vulkan/vulkan_image.cpp.o

src/vulkan/vulkan_image.i: src/vulkan/vulkan_image.cpp.i
.PHONY : src/vulkan/vulkan_image.i

# target to preprocess a source file
src/vulkan/vulkan_image.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_vulkan.dir/build.make CMakeFiles/zq_vulkan.dir/src/vulkan/vulkan_image.cpp.i
.PHONY : src/vulkan/vulkan_image.cpp.i

src/vulkan/vulkan_image.s: src/vulkan/vulkan_image.cpp.s
.PHONY : src/vulkan/vulkan_image.s

# target to generate assembly for a file
src/vulkan/vulkan_image.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_vulkan.dir/build.make CMakeFiles/zq_vulkan.dir/src/vulkan/vulkan_image.cpp.s
.PHONY : src/vulkan/vulkan_image.cpp.s

src/vulkan/vulkan_pipeline.o: src/vulkan/vulkan_pipeline.cpp.o
.PHONY : src/vulkan/vulkan_pipeline.o

# target to build an object file
src/vulkan/vulkan_pipeline.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_vulkan.dir/build.make CMakeFiles/zq_vulkan.dir/src/vulkan/vulkan_pipeline.cpp.o
.PHONY : src/vulkan/vulkan_pipeline.cpp.o

src/vulkan/vulkan_pipeline.i: src/vulkan/vulkan_pipeline.cpp.i
.PHONY : src/vulkan/vulkan_pipeline.i

# target to preprocess a source file
src/vulkan/vulkan_pipeline.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_vulkan.dir/build.make CMakeFiles/zq_vulkan.dir/src/vulkan/vulkan_pipeline.cpp.i
.PHONY : src/vulkan/vulkan_pipeline.cpp.i

src/vulkan/vulkan_pipeline.s: src/vulkan/vulkan_pipeline.cpp.s
.PHONY : src/vulkan/vulkan_pipeline.s

# target to generate assembly for a file
src/vulkan/vulkan_pipeline.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq_vulkan.dir/build.make CMakeFiles/zq_vulkan.dir/src/vulkan/vulkan_pipeline.cpp.s
.PHONY : src/vulkan/vulkan_pipeline.cpp.s

tests/core/bsp_test.o: tests/core/bsp_test.cpp.o
.PHONY : tests/core/bsp_test.o

# target to build an object file
tests/core/bsp_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_tests.dir/build.make CMakeFiles/zquake_tests.dir/tests/core/bsp_test.cpp.o
.PHONY : tests/core/bsp_test.cpp.o

tests/core/bsp_test.i: tests/core/bsp_test.cpp.i
.PHONY : tests/core/bsp_test.i

# target to preprocess a source file
tests/core/bsp_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_tests.dir/build.make CMakeFiles/zquake_tests.dir/tests/core/bsp_test.cpp.i
.PHONY : tests/core/bsp_test.cpp.i

tests/core/bsp_test.s: tests/core/bsp_test.cpp.s
.PHONY : tests/core/bsp_test.s

# target to generate assembly for a file
tests/core/bsp_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_tests.dir/build.make CMakeFiles/zquake_tests.dir/tests/core/bsp_test.cpp.s
.PHONY : tests/core/bsp_test.cpp.s

tests/core/console_test.o: tests/core/console_test.cpp.o
.PHONY : tests/core/console_test.o

# target to build an object file
tests/core/console_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_tests.dir/build.make CMakeFiles/zquake_tests.dir/tests/core/console_test.cpp.o
.PHONY : tests/core/console_test.cpp.o

tests/core/console_test.i: tests/core/console_test.cpp.i
.PHONY : tests/core/console_test.i

# target to preprocess a source file
tests/core/console_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_tests.dir/build.make CMakeFiles/zquake_tests.dir/tests/core/console_test.cpp.i
.PHONY : tests/core/console_test.cpp.i

tests/core/console_test.s: tests/core/console_test.cpp.s
.PHONY : tests/core/console_test.s

# target to generate assembly for a file
tests/core/console_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_tests.dir/build.make CMakeFiles/zquake_tests.dir/tests/core/console_test.cpp.s
.PHONY : tests/core/console_test.cpp.s

tests/core/container_test.o: tests/core/container_test.cpp.o
.PHONY : tests/core/container_test.o

# target to build an object file
tests/core/container_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_tests.dir/build.make CMakeFiles/zquake_tests.dir/tests/core/container_test.cpp.o
.PHONY : tests/core/container_test.cpp.o

tests/core/container_test.i: tests/core/container_test.cpp.i
.PHONY : tests/core/container_test.i

# target to preprocess a source file
tests/core/container_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_tests.dir/build.make CMakeFiles/zquake_tests.dir/tests/core/container_test.cpp.i
.PHONY : tests/core/container_test.cpp.i

tests/core/container_test.s: tests/core/container_test.cpp.s
.PHONY : tests/core/container_test.s

# target to generate assembly for a file
tests/core/container_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_tests.dir/build.make CMakeFiles/zquake_tests.dir/tests/core/container_test.cpp.s
.PHONY : tests/core/container_test.cpp.s

tests/core/fixed_test.o: tests/core/fixed_test.cpp.o
.PHONY : tests/core/fixed_test.o

# target to build an object file
tests/core/fixed_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_tests.dir/build.make CMakeFiles/zquake_tests.dir/tests/core/fixed_test.cpp.o
.PHONY : tests/core/fixed_test.cpp.o

tests/core/fixed_test.i: tests/core/fixed_test.cpp.i
.PHONY : tests/core/fixed_test.i

# target to preprocess a source file
tests/core/fixed_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_tests.dir/build.make CMakeFiles/zquake_tests.dir/tests/core/fixed_test.cpp.i
.PHONY : tests/core/fixed_test.cpp.i

tests/core/fixed_test.s: tests/core/fixed_test.cpp.s
.PHONY : tests/core/fixed_test.s

# target to generate assembly for a file
tests/core/fixed_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_tests.dir/build.make CMakeFiles/zquake_tests.dir/tests/core/fixed_test.cpp.s
.PHONY : tests/core/fixed_test.cpp.s

tests/core/gameplay_test.o: tests/core/gameplay_test.cpp.o
.PHONY : tests/core/gameplay_test.o

# target to build an object file
tests/core/gameplay_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_tests.dir/build.make CMakeFiles/zquake_tests.dir/tests/core/gameplay_test.cpp.o
.PHONY : tests/core/gameplay_test.cpp.o

tests/core/gameplay_test.i: tests/core/gameplay_test.cpp.i
.PHONY : tests/core/gameplay_test.i

# target to preprocess a source file
tests/core/gameplay_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_tests.dir/build.make CMakeFiles/zquake_tests.dir/tests/core/gameplay_test.cpp.i
.PHONY : tests/core/gameplay_test.cpp.i

tests/core/gameplay_test.s: tests/core/gameplay_test.cpp.s
.PHONY : tests/core/gameplay_test.s

# target to generate assembly for a file
tests/core/gameplay_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_tests.dir/build.make CMakeFiles/zquake_tests.dir/tests/core/gameplay_test.cpp.s
.PHONY : tests/core/gameplay_test.cpp.s

tests/core/memory_test.o: tests/core/memory_test.cpp.o
.PHONY : tests/core/memory_test.o

# target to build an object file
tests/core/memory_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_tests.dir/build.make CMakeFiles/zquake_tests.dir/tests/core/memory_test.cpp.o
.PHONY : tests/core/memory_test.cpp.o

tests/core/memory_test.i: tests/core/memory_test.cpp.i
.PHONY : tests/core/memory_test.i

# target to preprocess a source file
tests/core/memory_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_tests.dir/build.make CMakeFiles/zquake_tests.dir/tests/core/memory_test.cpp.i
.PHONY : tests/core/memory_test.cpp.i

tests/core/memory_test.s: tests/core/memory_test.cpp.s
.PHONY : tests/core/memory_test.s

# target to generate assembly for a file
tests/core/memory_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_tests.dir/build.make CMakeFiles/zquake_tests.dir/tests/core/memory_test.cpp.s
.PHONY : tests/core/memory_test.cpp.s

tests/core/move_test.o: tests/core/move_test.cpp.o
.PHONY : tests/core/move_test.o

# target to build an object file
tests/core/move_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_tests.dir/build.make CMakeFiles/zquake_tests.dir/tests/core/move_test.cpp.o
.PHONY : tests/core/move_test.cpp.o

tests/core/move_test.i: tests/core/move_test.cpp.i
.PHONY : tests/core/move_test.i

# target to preprocess a source file
tests/core/move_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_tests.dir/build.make CMakeFiles/zquake_tests.dir/tests/core/move_test.cpp.i
.PHONY : tests/core/move_test.cpp.i

tests/core/move_test.s: tests/core/move_test.cpp.s
.PHONY : tests/core/move_test.s

# target to generate assembly for a file
tests/core/move_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_tests.dir/build.make CMakeFiles/zquake_tests.dir/tests/core/move_test.cpp.s
.PHONY : tests/core/move_test.cpp.s

tests/core/progs_vm_test.o: tests/core/progs_vm_test.cpp.o
.PHONY : tests/core/progs_vm_test.o

# target to build an object file
tests/core/progs_vm_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_tests.dir/build.make CMakeFiles/zquake_tests.dir/tests/core/progs_vm_test.cpp.o
.PHONY : tests/core/progs_vm_test.cpp.o

tests/core/progs_vm_test.i: tests/core/progs_vm_test.cpp.i
.PHONY : tests/core/progs_vm_test.i

# target to preprocess a source file
tests/core/progs_vm_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_tests.dir/build.make CMakeFiles/zquake_tests.dir/tests/core/progs_vm_test.cpp.i
.PHONY : tests/core/progs_vm_test.cpp.i

tests/core/progs_vm_test.s: tests/core/progs_vm_test.cpp.s
.PHONY : tests/core/progs_vm_test.s

# target to generate assembly for a file
tests/core/progs_vm_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_tests.dir/build.make CMakeFiles/zquake_tests.dir/tests/core/progs_vm_test.cpp.s
.PHONY : tests/core/progs_vm_test.cpp.s

tests/core/ray_scene_test.o: tests/core/ray_scene_test.cpp.o
.PHONY : tests/core/ray_scene_test.o

# target to build an object file
tests/core/ray_scene_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_tests.dir/build.make CMakeFiles/zquake_tests.dir/tests/core/ray_scene_test.cpp.o
.PHONY : tests/core/ray_scene_test.cpp.o

tests/core/ray_scene_test.i: tests/core/ray_scene_test.cpp.i
.PHONY : tests/core/ray_scene_test.i

# target to preprocess a source file
tests/core/ray_scene_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_tests.dir/build.make CMakeFiles/zquake_tests.dir/tests/core/ray_scene_test.cpp.i
.PHONY : tests/core/ray_scene_test.cpp.i

tests/core/ray_scene_test.s: tests/core/ray_scene_test.cpp.s
.PHONY : tests/core/ray_scene_test.s

# target to generate assembly for a file
tests/core/ray_scene_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_tests.dir/build.make CMakeFiles/zquake_tests.dir/tests/core/ray_scene_test.cpp.s
.PHONY : tests/core/ray_scene_test.cpp.s

tests/core/vm_test.o: tests/core/vm_test.cpp.o
.PHONY : tests/core/vm_test.o

# target to build an object file
tests/core/vm_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_tests.dir/build.make CMakeFiles/zquake_tests.dir/tests/core/vm_test.cpp.o
.PHONY : tests/core/vm_test.cpp.o

tests/core/vm_test.i: tests/core/vm_test.cpp.i
.PHONY : tests/core/vm_test.i

# target to preprocess a source file
tests/core/vm_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_tests.dir/build.make CMakeFiles/zquake_tests.dir/tests/core/vm_test.cpp.i
.PHONY : tests/core/vm_test.cpp.i

tests/core/vm_test.s: tests/core/vm_test.cpp.s
.PHONY : tests/core/vm_test.s

# target to generate assembly for a file
tests/core/vm_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_tests.dir/build.make CMakeFiles/zquake_tests.dir/tests/core/vm_test.cpp.s
.PHONY : tests/core/vm_test.cpp.s

tests/filesystem/fs_test.o: tests/filesystem/fs_test.cpp.o
.PHONY : tests/filesystem/fs_test.o

# target to build an object file
tests/filesystem/fs_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_tests.dir/build.make CMakeFiles/zquake_tests.dir/tests/filesystem/fs_test.cpp.o
.PHONY : tests/filesystem/fs_test.cpp.o

tests/filesystem/fs_test.i: tests/filesystem/fs_test.cpp.i
.PHONY : tests/filesystem/fs_test.i

# target to preprocess a source file
tests/filesystem/fs_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_tests.dir/build.make CMakeFiles/zquake_tests.dir/tests/filesystem/fs_test.cpp.i
.PHONY : tests/filesystem/fs_test.cpp.i

tests/filesystem/fs_test.s: tests/filesystem/fs_test.cpp.s
.PHONY : tests/filesystem/fs_test.s

# target to generate assembly for a file
tests/filesystem/fs_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_tests.dir/build.make CMakeFiles/zquake_tests.dir/tests/filesystem/fs_test.cpp.s
.PHONY : tests/filesystem/fs_test.cpp.s

tests/inspect_models.o: tests/inspect_models.cpp.o
.PHONY : tests/inspect_models.o

# target to build an object file
tests/inspect_models.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_inspect.dir/build.make CMakeFiles/zquake_inspect.dir/tests/inspect_models.cpp.o
.PHONY : tests/inspect_models.cpp.o

tests/inspect_models.i: tests/inspect_models.cpp.i
.PHONY : tests/inspect_models.i

# target to preprocess a source file
tests/inspect_models.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_inspect.dir/build.make CMakeFiles/zquake_inspect.dir/tests/inspect_models.cpp.i
.PHONY : tests/inspect_models.cpp.i

tests/inspect_models.s: tests/inspect_models.cpp.s
.PHONY : tests/inspect_models.s

# target to generate assembly for a file
tests/inspect_models.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_inspect.dir/build.make CMakeFiles/zquake_inspect.dir/tests/inspect_models.cpp.s
.PHONY : tests/inspect_models.cpp.s

tests/main.o: tests/main.cpp.o
.PHONY : tests/main.o

# target to build an object file
tests/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_tests.dir/build.make CMakeFiles/zquake_tests.dir/tests/main.cpp.o
.PHONY : tests/main.cpp.o

tests/main.i: tests/main.cpp.i
.PHONY : tests/main.i

# target to preprocess a source file
tests/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_tests.dir/build.make CMakeFiles/zquake_tests.dir/tests/main.cpp.i
.PHONY : tests/main.cpp.i

tests/main.s: tests/main.cpp.s
.PHONY : tests/main.s

# target to generate assembly for a file
tests/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_tests.dir/build.make CMakeFiles/zquake_tests.dir/tests/main.cpp.s
.PHONY : tests/main.cpp.s

tests/orientation_test.o: tests/orientation_test.cpp.o
.PHONY : tests/orientation_test.o

# target to build an object file
tests/orientation_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_orientation.dir/build.make CMakeFiles/zquake_orientation.dir/tests/orientation_test.cpp.o
.PHONY : tests/orientation_test.cpp.o

tests/orientation_test.i: tests/orientation_test.cpp.i
.PHONY : tests/orientation_test.i

# target to preprocess a source file
tests/orientation_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_orientation.dir/build.make CMakeFiles/zquake_orientation.dir/tests/orientation_test.cpp.i
.PHONY : tests/orientation_test.cpp.i

tests/orientation_test.s: tests/orientation_test.cpp.s
.PHONY : tests/orientation_test.s

# target to generate assembly for a file
tests/orientation_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_orientation.dir/build.make CMakeFiles/zquake_orientation.dir/tests/orientation_test.cpp.s
.PHONY : tests/orientation_test.cpp.s

tests/raytrace_test.o: tests/raytrace_test.cpp.o
.PHONY : tests/raytrace_test.o

# target to build an object file
tests/raytrace_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_raytrace.dir/build.make CMakeFiles/zquake_raytrace.dir/tests/raytrace_test.cpp.o
.PHONY : tests/raytrace_test.cpp.o

tests/raytrace_test.i: tests/raytrace_test.cpp.i
.PHONY : tests/raytrace_test.i

# target to preprocess a source file
tests/raytrace_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_raytrace.dir/build.make CMakeFiles/zquake_raytrace.dir/tests/raytrace_test.cpp.i
.PHONY : tests/raytrace_test.cpp.i

tests/raytrace_test.s: tests/raytrace_test.cpp.s
.PHONY : tests/raytrace_test.s

# target to generate assembly for a file
tests/raytrace_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_raytrace.dir/build.make CMakeFiles/zquake_raytrace.dir/tests/raytrace_test.cpp.s
.PHONY : tests/raytrace_test.cpp.s

tests/real_data_test.o: tests/real_data_test.cpp.o
.PHONY : tests/real_data_test.o

# target to build an object file
tests/real_data_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_realdata.dir/build.make CMakeFiles/zquake_realdata.dir/tests/real_data_test.cpp.o
.PHONY : tests/real_data_test.cpp.o

tests/real_data_test.i: tests/real_data_test.cpp.i
.PHONY : tests/real_data_test.i

# target to preprocess a source file
tests/real_data_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_realdata.dir/build.make CMakeFiles/zquake_realdata.dir/tests/real_data_test.cpp.i
.PHONY : tests/real_data_test.cpp.i

tests/real_data_test.s: tests/real_data_test.cpp.s
.PHONY : tests/real_data_test.s

# target to generate assembly for a file
tests/real_data_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_realdata.dir/build.make CMakeFiles/zquake_realdata.dir/tests/real_data_test.cpp.s
.PHONY : tests/real_data_test.cpp.s

tests/spawn_view.o: tests/spawn_view.cpp.o
.PHONY : tests/spawn_view.o

# target to build an object file
tests/spawn_view.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_spawnview.dir/build.make CMakeFiles/zquake_spawnview.dir/tests/spawn_view.cpp.o
.PHONY : tests/spawn_view.cpp.o

tests/spawn_view.i: tests/spawn_view.cpp.i
.PHONY : tests/spawn_view.i

# target to preprocess a source file
tests/spawn_view.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_spawnview.dir/build.make CMakeFiles/zquake_spawnview.dir/tests/spawn_view.cpp.i
.PHONY : tests/spawn_view.cpp.i

tests/spawn_view.s: tests/spawn_view.cpp.s
.PHONY : tests/spawn_view.s

# target to generate assembly for a file
tests/spawn_view.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_spawnview.dir/build.make CMakeFiles/zquake_spawnview.dir/tests/spawn_view.cpp.s
.PHONY : tests/spawn_view.cpp.s

tests/vulkan_smoke.o: tests/vulkan_smoke.cpp.o
.PHONY : tests/vulkan_smoke.o

# target to build an object file
tests/vulkan_smoke.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_smoke.dir/build.make CMakeFiles/zquake_smoke.dir/tests/vulkan_smoke.cpp.o
.PHONY : tests/vulkan_smoke.cpp.o

tests/vulkan_smoke.i: tests/vulkan_smoke.cpp.i
.PHONY : tests/vulkan_smoke.i

# target to preprocess a source file
tests/vulkan_smoke.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_smoke.dir/build.make CMakeFiles/zquake_smoke.dir/tests/vulkan_smoke.cpp.i
.PHONY : tests/vulkan_smoke.cpp.i

tests/vulkan_smoke.s: tests/vulkan_smoke.cpp.s
.PHONY : tests/vulkan_smoke.s

# target to generate assembly for a file
tests/vulkan_smoke.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zquake_smoke.dir/build.make CMakeFiles/zquake_smoke.dir/tests/vulkan_smoke.cpp.s
.PHONY : tests/vulkan_smoke.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... shaders"
	@echo "... Catch2"
	@echo "... Catch2WithMain"
	@echo "... zq_core"
	@echo "... zq_engine"
	@echo "... zq_filesystem"
	@echo "... zq_render"
	@echo "... zq_subsystems"
	@echo "... zq_vm"
	@echo "... zq_vulkan"
	@echo "... zquake"
	@echo "... zquake_inspect"
	@echo "... zquake_orientation"
	@echo "... zquake_raytrace"
	@echo "... zquake_realdata"
	@echo "... zquake_smoke"
	@echo "... zquake_spawnview"
	@echo "... zquake_tests"
	@echo "... src/app/entry_point.o"
	@echo "... src/app/entry_point.i"
	@echo "... src/app/entry_point.s"
	@echo "... src/app/rt_scene.o"
	@echo "... src/app/rt_scene.i"
	@echo "... src/app/rt_scene.s"
	@echo "... src/app/world_builder.o"
	@echo "... src/app/world_builder.i"
	@echo "... src/app/world_builder.s"
	@echo "... src/core/container/string.o"
	@echo "... src/core/container/string.i"
	@echo "... src/core/container/string.s"
	@echo "... src/core/fixed/fixed_math.o"
	@echo "... src/core/fixed/fixed_math.i"
	@echo "... src/core/fixed/fixed_math.s"
	@echo "... src/core/fixed/fixed_t.o"
	@echo "... src/core/fixed/fixed_t.i"
	@echo "... src/core/fixed/fixed_t.s"
	@echo "... src/core/fixed/fixed_tables.o"
	@echo "... src/core/fixed/fixed_tables.i"
	@echo "... src/core/fixed/fixed_tables.s"
	@echo "... src/core/io/file_io.o"
	@echo "... src/core/io/file_io.i"
	@echo "... src/core/io/file_io.s"
	@echo "... src/core/logging/logger.o"
	@echo "... src/core/logging/logger.i"
	@echo "... src/core/logging/logger.s"
	@echo "... src/core/memory/allocator.o"
	@echo "... src/core/memory/allocator.i"
	@echo "... src/core/memory/allocator.s"
	@echo "... src/engine/area_nodes.o"
	@echo "... src/engine/area_nodes.i"
	@echo "... src/engine/area_nodes.s"
	@echo "... src/engine/bsp.o"
	@echo "... src/engine/bsp.i"
	@echo "... src/engine/bsp.s"
	@echo "... src/engine/console.o"
	@echo "... src/engine/console.i"
	@echo "... src/engine/console.s"
	@echo "... src/engine/cvar_parser.o"
	@echo "... src/engine/cvar_parser.i"
	@echo "... src/engine/cvar_parser.s"
	@echo "... src/engine/cvar_system.o"
	@echo "... src/engine/cvar_system.i"
	@echo "... src/engine/cvar_system.s"
	@echo "... src/engine/entity.o"
	@echo "... src/engine/entity.i"
	@echo "... src/engine/entity.s"
	@echo "... src/engine/game.o"
	@echo "... src/engine/game.i"
	@echo "... src/engine/game.s"
	@echo "... src/engine/game_builtins.o"
	@echo "... src/engine/game_builtins.i"
	@echo "... src/engine/game_builtins.s"
	@echo "... src/engine/gameframe.o"
	@echo "... src/engine/gameframe.i"
	@echo "... src/engine/gameframe.s"
	@echo "... src/engine/host.o"
	@echo "... src/engine/host.i"
	@echo "... src/engine/host.s"
	@echo "... src/engine/input.o"
	@echo "... src/engine/input.i"
	@echo "... src/engine/input.s"
	@echo "... src/engine/mdl_model.o"
	@echo "... src/engine/mdl_model.i"
	@echo "... src/engine/mdl_model.s"
	@echo "... src/engine/model.o"
	@echo "... src/engine/model.i"
	@echo "... src/engine/model.s"
	@echo "... src/engine/monster_move.o"
	@echo "... src/engine/monster_move.i"
	@echo "... src/engine/monster_move.s"
	@echo "... src/engine/move.o"
	@echo "... src/engine/move.i"
	@echo "... src/engine/move.s"
	@echo "... src/engine/particle.o"
	@echo "... src/engine/particle.i"
	@echo "... src/engine/particle.s"
	@echo "... src/engine/world.o"
	@echo "... src/engine/world.i"
	@echo "... src/engine/world.s"
	@echo "... src/filesystem/pak_archive.o"
	@echo "... src/filesystem/pak_archive.i"
	@echo "... src/filesystem/pak_archive.s"
	@echo "... src/filesystem/path_util.o"
	@echo "... src/filesystem/path_util.i"
	@echo "... src/filesystem/path_util.s"
	@echo "... src/filesystem/virtual_fs.o"
	@echo "... src/filesystem/virtual_fs.i"
	@echo "... src/filesystem/virtual_fs.s"
	@echo "... src/render/font8x8.o"
	@echo "... src/render/font8x8.i"
	@echo "... src/render/font8x8.s"
	@echo "... src/render/ray_scene.o"
	@echo "... src/render/ray_scene.i"
	@echo "... src/render/ray_scene.s"
	@echo "... src/render/raytracer.o"
	@echo "... src/render/raytracer.i"
	@echo "... src/render/raytracer.s"
	@echo "... src/render/software_renderer.o"
	@echo "... src/render/software_renderer.i"
	@echo "... src/render/software_renderer.s"
	@echo "... src/subsystems/client.o"
	@echo "... src/subsystems/client.i"
	@echo "... src/subsystems/client.s"
	@echo "... src/subsystems/net_addr.o"
	@echo "... src/subsystems/net_addr.i"
	@echo "... src/subsystems/net_addr.s"
	@echo "... src/subsystems/net_driver.o"
	@echo "... src/subsystems/net_driver.i"
	@echo "... src/subsystems/net_driver.s"
	@echo "... src/subsystems/protocol.o"
	@echo "... src/subsystems/protocol.i"
	@echo "... src/subsystems/protocol.s"
	@echo "... src/subsystems/reliable_channel.o"
	@echo "... src/subsystems/reliable_channel.i"
	@echo "... src/subsystems/reliable_channel.s"
	@echo "... src/subsystems/server.o"
	@echo "... src/subsystems/server.i"
	@echo "... src/subsystems/server.s"
	@echo "... src/vm/builtin_registry.o"
	@echo "... src/vm/builtin_registry.i"
	@echo "... src/vm/builtin_registry.s"
	@echo "... src/vm/bytecode.o"
	@echo "... src/vm/bytecode.i"
	@echo "... src/vm/bytecode.s"
	@echo "... src/vm/libstd/cl_parse.o"
	@echo "... src/vm/libstd/cl_parse.i"
	@echo "... src/vm/libstd/cl_parse.s"
	@echo "... src/vm/libstd/pr_edict.o"
	@echo "... src/vm/libstd/pr_edict.i"
	@echo "... src/vm/libstd/pr_edict.s"
	@echo "... src/vm/libstd/sv_globals.o"
	@echo "... src/vm/libstd/sv_globals.i"
	@echo "... src/vm/libstd/sv_globals.s"
	@echo "... src/vm/opcode.o"
	@echo "... src/vm/opcode.i"
	@echo "... src/vm/opcode.s"
	@echo "... src/vm/prog_builtins.o"
	@echo "... src/vm/prog_builtins.i"
	@echo "... src/vm/prog_builtins.s"
	@echo "... src/vm/prog_vm.o"
	@echo "... src/vm/prog_vm.i"
	@echo "... src/vm/prog_vm.s"
	@echo "... src/vm/vm.o"
	@echo "... src/vm/vm.i"
	@echo "... src/vm/vm.s"
	@echo "... src/vulkan/command_pool.o"
	@echo "... src/vulkan/command_pool.i"
	@echo "... src/vulkan/command_pool.s"
	@echo "... src/vulkan/render_command.o"
	@echo "... src/vulkan/render_command.i"
	@echo "... src/vulkan/render_command.s"
	@echo "... src/vulkan/render_thread.o"
	@echo "... src/vulkan/render_thread.i"
	@echo "... src/vulkan/render_thread.s"
	@echo "... src/vulkan/vulkan_api.o"
	@echo "... src/vulkan/vulkan_api.i"
	@echo "... src/vulkan/vulkan_api.s"
	@echo "... src/vulkan/vulkan_buffer.o"
	@echo "... src/vulkan/vulkan_buffer.i"
	@echo "... src/vulkan/vulkan_buffer.s"
	@echo "... src/vulkan/vulkan_image.o"
	@echo "... src/vulkan/vulkan_image.i"
	@echo "... src/vulkan/vulkan_image.s"
	@echo "... src/vulkan/vulkan_pipeline.o"
	@echo "... src/vulkan/vulkan_pipeline.i"
	@echo "... src/vulkan/vulkan_pipeline.s"
	@echo "... tests/core/bsp_test.o"
	@echo "... tests/core/bsp_test.i"
	@echo "... tests/core/bsp_test.s"
	@echo "... tests/core/console_test.o"
	@echo "... tests/core/console_test.i"
	@echo "... tests/core/console_test.s"
	@echo "... tests/core/container_test.o"
	@echo "... tests/core/container_test.i"
	@echo "... tests/core/container_test.s"
	@echo "... tests/core/fixed_test.o"
	@echo "... tests/core/fixed_test.i"
	@echo "... tests/core/fixed_test.s"
	@echo "... tests/core/gameplay_test.o"
	@echo "... tests/core/gameplay_test.i"
	@echo "... tests/core/gameplay_test.s"
	@echo "... tests/core/memory_test.o"
	@echo "... tests/core/memory_test.i"
	@echo "... tests/core/memory_test.s"
	@echo "... tests/core/move_test.o"
	@echo "... tests/core/move_test.i"
	@echo "... tests/core/move_test.s"
	@echo "... tests/core/progs_vm_test.o"
	@echo "... tests/core/progs_vm_test.i"
	@echo "... tests/core/progs_vm_test.s"
	@echo "... tests/core/ray_scene_test.o"
	@echo "... tests/core/ray_scene_test.i"
	@echo "... tests/core/ray_scene_test.s"
	@echo "... tests/core/vm_test.o"
	@echo "... tests/core/vm_test.i"
	@echo "... tests/core/vm_test.s"
	@echo "... tests/filesystem/fs_test.o"
	@echo "... tests/filesystem/fs_test.i"
	@echo "... tests/filesystem/fs_test.s"
	@echo "... tests/inspect_models.o"
	@echo "... tests/inspect_models.i"
	@echo "... tests/inspect_models.s"
	@echo "... tests/main.o"
	@echo "... tests/main.i"
	@echo "... tests/main.s"
	@echo "... tests/orientation_test.o"
	@echo "... tests/orientation_test.i"
	@echo "... tests/orientation_test.s"
	@echo "... tests/raytrace_test.o"
	@echo "... tests/raytrace_test.i"
	@echo "... tests/raytrace_test.s"
	@echo "... tests/real_data_test.o"
	@echo "... tests/real_data_test.i"
	@echo "... tests/real_data_test.s"
	@echo "... tests/spawn_view.o"
	@echo "... tests/spawn_view.i"
	@echo "... tests/spawn_view.s"
	@echo "... tests/vulkan_smoke.o"
	@echo "... tests/vulkan_smoke.i"
	@echo "... tests/vulkan_smoke.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

